import * as React from "react";
import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home({
  data,
}: {
  data: { name: string; hair_color: string; skin_color: string };
}) {
  const [count, setCount] = React.useState(0);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          <a href="/" className={styles.card} rel="noopener noreferrer">
            <h2 className={inter.className}>
              <span>&lt;-</span> Portal
            </h2>
            <p className={inter.className}>Back Portal</p>
          </a>
          <div className={styles.description}>
            <h1>This is App 1</h1>
            <p>count: {count}</p>
            <button onClick={() => setCount(prev => (prev += 1))}>
              INCREMENT
            </button>
            <p>name: {data.name}</p>
            <p>hair color: {data.hair_color}</p>
            <p>skin color: {data.skin_color}</p>
          </div>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const response = await fetch("https://swapi.dev/api/people/1/");
  const data = await response.json();

  return {
    props: {
      data,
    },
  };
}
